### GET /webhooks
GET http://localhost:8000/webhooks


### POST /webhooks/deleteTask
POST http://localhost:8000/webhooks/deleteTask
Content-Type: application/json

{
  "task_id": "5ecjat"
}

### POST /webhooks/updateEstimate
POST http://localhost:8000/webhooks/updateEstimate
Content-Type: application/json

{
  "task_id": "5ecjat",
  "history_items": [
    {"after": 21600000}
  ]
}

### POST /webhooks/updateDueDate
POST http://localhost:8000/webhooks/updateDueDate
Content-Type: application/json

{
  "task_id": "5ecjat",
  "history_items": [
    {"after": 1584442800000}
  ]
}